# -*- coding: utf-8 -*-
"""Grokking_in_Transformer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TTwNPkQb84CNDFe2aL2DDXMO7peY0MB6

Feature	GrokkingTransformer (Modular Addition)	AbacusTransformer (Decimal Addition)
Task Type	Classification	Sequence-to-Sequence (Seq2Seq)
Input	Two single tokens (a, b). Fixed length.	A sequence of digit tokens (1, 2, +, 3, 4). Variable length.
Output	A single token (c).	A sequence of digit tokens (4, 6, <eos>). Variable length.
Core Challenge	Discover a hidden periodic pattern in a closed set.	Learn a multi-step, stateful algorithm (column-by-column addition with carries).
Generalization	Interpolate within the 113x113 grid.	Extrapolate to longer sequences and numbers never seen before (length generalization).

2. The Model's Challenge:
A transformer is just a sequence of matrix multiplications and simple non-linearities (ReLU, Softmax). How can a stack of linear operations learn a "wrapping around" function? It needs a trick. The most elegant trick is to stop representing numbers as distinct points on a line and start representing them as vectors on a circle. In this representation, "adding" numbers becomes equivalent to rotating vectors.

## TODO
* PCA/TSNE on the embeddings
* find rotation matrix

Best score (small)
d_ffn: 512
d_model: 64
lr: 0.001
seed: 42
weight_decay: 2.5
"""

!pip install transformer_lens torchinfo torchviz umap-learn git+https://github.com/neelnanda-io/neel-plotly.git
5

import numpy as np
import einops
from fancy_einsum import einsum
import os
import tqdm.auto as tqdm
import random
from pathlib import Path
import plotly.express as px
import torch
import torch.nn as nn
import wandb
from transformer_lens import HookedTransformer, HookedTransformerConfig

device = "cuda" if torch.cuda.is_available() else "cpu"

def get_data(config: dict):
    """
    Generates the dataset for the modular arithmetic task (a + b) % p.

    This version is modified to be memory-efficient by sampling directly,
    rather than creating the full p*p table. The core theory remains.

    Theory:
    - Task Design: Modular arithmetic is a classic algorithmic task used to study "grokking."
      It's simple to specify but requires the model to learn a non-trivial, periodic structure.
      The entire dataset is finite and can be perfectly learned.
    - Tokenization: The inputs `a` and `b` and the special "equals" token are represented as integers.
      `p` is used as the "equals" token, signifying the position where the model should output the answer.
      This transforms a math problem into a standard seq-to-seq prediction task.
    - Data Split: A small training set (frac_train) and a large test set are used. This setup is
      CRUCIAL for observing grokking. The model first memorizes the small training set (achieving low
      train loss but high test loss) and only much later, after extensive training, does it "grok"
      the underlying pattern, causing test accuracy to suddenly spike.
    """
    p, n_examples, frac_train, device = config['p'], config['n_examples'], config['frac_train'], config['device']

    # Sample 'n_examples' pairs of (a, b) directly to avoid memory issues with large p.
    a = torch.randint(0, p, (n_examples,), device=device)
    b = torch.randint(0, p, (n_examples,), device=device)

    # Create prompts and labels from the sampled pairs.
    prompts = torch.stack([
        a,
        b,
        torch.full((n_examples,), p, device=device) # The 'p' token acts as our '=' sign.
    ], dim=1)
    labels = (a + b) % p

    # Randomly shuffle to ensure the train/test sets are not structured.
    indices = torch.randperm(n_examples, device=device)
    cutoff = int(n_examples * frac_train)
    train_indices, test_indices = indices[:cutoff], indices[cutoff:]

    train_data, test_data = prompts[train_indices], prompts[test_indices]
    train_labels, test_labels = labels[train_indices], labels[test_indices]

    return train_data, train_labels, test_data, test_labels

def gini(x):
    """
    Calculates the Gini coefficient, a measure of inequality or sparsity.

    Theory:
    - Sparsity: In neural networks, a sparse representation is one where most neurons are inactive (close to zero).
      A high Gini coefficient (close to 1) implies high sparsity.
    - Interpretability: Sparse representations are often considered more interpretable. If only a few
      neurons are active for a given input, it's easier to attribute meaning to those neurons.
      Tracking the Gini coefficient of embeddings and other weight matrices can indicate whether the
      model is learning a sparse, structured solution.
    """
    x = torch.abs(x.flatten())
    if torch.sum(x) == 0: return 0.0
    x = torch.sort(x)[0] # Sort values in ascending order
    n = len(x)
    cumx = torch.cumsum(x, dim=0)
    # The Gini formula, normalized.
    return (n + 1 - 2 * torch.sum(cumx) / cumx[-1]) / n

@torch.no_grad()
def evaluate(model: HookedTransformer, test_data, test_labels, config: dict):
    """
    Evaluates the model on the test set.

    Theory:
    - Test Accuracy vs. Loss: The key metric for grokking. We expect test accuracy to remain near random
      for a long time, even as training loss drops. The "grokking" moment is when test accuracy
      suddenly jumps to ~100%.
    - L2 Norm: This is the sum of the squares of all model parameters. It's a measure of the model's complexity.
      In grokking literature, it's observed that models often find a simpler (lower L2 norm) solution
      during the phase transition to generalization.
    - Gini Coefficients (Embed/Unembed): Tracking the sparsity of the embedding (W_E) and
      unembedding (W_U) matrices. An increase in Gini suggests the model is learning to represent
      numbers in a more structured, sparse way (e.g., via a Fourier basis) rather than as
      opaque, dense vectors.
    """
    model.eval()
    logits = model(test_data)[:, -1, :]
    test_loss = nn.CrossEntropyLoss()(logits, test_labels).item()
    test_acc = (torch.argmax(logits, dim=-1) == test_labels).float().mean().item()
    l2_norm = sum(p.pow(2).sum() for p in model.parameters()).item()

    W_E = model.W_E[:config['p'], :]
    W_U = model.W_U[:, :config['p']]
    gini_embed = gini(W_E).item()
    gini_unembed = gini(W_U.T).item()

    return {
        'test_loss': test_loss, 'test_acc': test_acc, 'l2_norm': l2_norm,
        'gini_embed': gini_embed, 'gini_unembed': gini_unembed
    }

def train(config: dict,  train_data, train_labels, test_data, test_labels):
    """
    Takes a config dict, trains a model, logs to wandb, and returns the model and a history of metrics.
    """
    torch.manual_seed(config['seed'])
    np.random.seed(config['seed'])

    # Theory: Model Configuration
    # - Small Model: The model is intentionally small (1 layer, small d_model). This makes it
    #   harder to simply memorize the entire p*p table via brute force, encouraging it to find
    #   the underlying algorithmic structure.
    # - d_vocab = p + 1: We need tokens for numbers 0 to p-1, plus one special token for '='.
    # - n_ctx = 3: The context length is fixed at 3 because our input is always `(a, b, =)`.
    model_config = HookedTransformerConfig(
        n_layers=config['n_layers'], n_heads=config['n_head'], d_model=config['d_model'],
        d_head=config['d_model'] // config['n_head'], d_mlp=config['d_ffn'], d_vocab=config['p'] + 1,
        n_ctx=3, act_fn="relu", normalization_type=None, device=config['device'],
    )
    model = HookedTransformer(model_config)

    # Theory: Zeroing out W_U
    # - This is a very specific and unusual choice. Typically W_U is tied to W_E or learned.
    # - By zeroing it, we force the model to learn the mapping from its internal representations
    #   to output logits from scratch. This may create a cleaner separation between the model's
    #   internal "computation" and its "output formatting," making analysis easier. It ensures
    #   that any initial structure comes purely from the embedding and processing, not the unembedding.
    with torch.no_grad():
        model.W_U.data.zero_()

    # Theory: Optimizer
    # - AdamW: A standard, robust optimizer.
    # - Weight Decay: This is a critical hyperparameter. High weight decay penalizes large weights,
    #   acting as a form of regularization. In grokking, weight decay is thought to be a key driver,
    #   pushing the model away from complex, memorizing solutions towards simpler, generalizing ones.
    #   The value of `weight_decay` can dramatically affect whether and when grokking occurs.
    optimizer = torch.optim.AdamW(model.parameters(), lr=config['lr'], weight_decay=config['weight_decay'])

    # Initialize a history dictionary to store metrics over time
    history = {
        'steps': [], 'train_loss': [], 'test_loss': [], 'test_acc': [],
        'l2_norm': [], 'gini_embed': [], 'gini_unembed': []
    }

    for step in range(config['steps']):
        model.train()
        logits = model(train_data)[:, -1, :]

        # Theory: Loss Calculation
        # - The choice `nn.CrossEntropyLoss()(logits, train_labels)` computes loss over all p+1
        #   possible output tokens. This means the model is penalized if it assigns high probability
        #   to the special '=' token (p) in the output position, which is desirable.
        # - The alternative, `logits[:, :config['p']]`, would ignore the logit for the '=' token.
        #   The comment in your original code suggests this has an effect on the Gini coefficient,
        #   likely because forcing the logit for token 'p' to be low might distribute probability
        #   mass differently across the other tokens, affecting sparsity.
        loss = nn.CrossEntropyLoss()(logits, train_labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if wandb.run and (step % config['eval_interval'] == 0 or step == config['steps'] - 1):
            metrics = evaluate(model, test_data, test_labels, config)
            metrics['train_loss'] = loss.item()
            wandb.log(metrics, step=step)

            # Append current metrics to the history object
            history['steps'].append(step)
            history['train_loss'].append(metrics['train_loss'])
            history['test_loss'].append(metrics['test_loss'])
            history['test_acc'].append(metrics['test_acc'])
            history['l2_norm'].append(metrics['l2_norm'])
            history['gini_embed'].append(metrics['gini_embed'])
            history['gini_unembed'].append(metrics['gini_unembed'])

    # Return the trained model AND the full history of metrics
    return model, history

# Best score (small)
# d_ffn: 512
# d_model: 64
# lr: 0.001
# seed: 42
# weight_decay: 1 # or 2.5
config = {
    'p': 113, #SHOULD BE PRIME NUMBER!
    'n_examples': 113*113,
    'frac_train': 0.3,
    'n_layers': 1,
    'n_head': 3,
    'd_model': 32,
    'd_ffn': 128,
    'lr': 1e-3,
    'weight_decay': 4,
    'steps': 60001,
    'eval_interval': 1000,
    'seed': 43,
    'device': "cuda" if torch.cuda.is_available() else "cpu"
}

# 2. Initialize W&B and run training directly
print(f"--- Starting Interactive Training (p={config['p']}) ---")
print(f"Device: {config['device']}")
print(f"Total examples: {config['n_examples']} ({int(config['n_examples']*config['frac_train'])} train / {int(config['n_examples']*(1-config['frac_train']))} test)")

train_data, train_labels, test_data, test_labels = get_data(config)

# Use a dummy wandb object if not running a full sweep, or install and login to wandb
# To run without wandb, you can comment out the `with wandb.init(...)` block and de-indent the line below it.
try:
    wandb.init(project="grokking-interactive-full-code", config=config)
    # Capture both the model and the history object from the train function
    trained_model, history = train(wandb.config, train_data, train_labels, test_data, test_labels)
    wandb.finish()
except Exception as e:
    print(f"Could not initialize wandb, running without it. Error: {e}")
    class DummyWandb:
        def __init__(self):
            self.run = None
            self.config = config
    # Run training without logging, still capturing the history
    trained_model, history = train(DummyWandb().config, train_data, train_labels, test_data, test_labels)


print("--- Training Finished ---")

# 3. The 'trained_model' and 'history' objects are now available for inspection
print("\nModel is available in the notebook scope:", trained_model is not None)
print("History object is available:", history is not None)
print("Available history keys:", list(history.keys()))

model = trained_model

model = trained_model

from google.colab import drive
if False: #if loading the model from drive
    MODEL_PATH = "/content/drive/MyDrive/grokking_run/model_state_dict.pt"
    p = config["p"]

    drive.mount('/content/drive')
    model_config = HookedTransformerConfig(
        n_layers=config['n_layers'], n_heads=config['n_head'], d_model=config['d_model'],
        d_head=config['d_model'] // config['n_head'], d_mlp=config['d_ffn'], d_vocab=config['p'] + 1,
        n_ctx=3, act_fn="relu", normalization_type=None, device=config['device'],
    )
    model = HookedTransformer(model_config)
    model.load_state_dict(torch.load(MODEL_PATH))
    history = torch.load(HISTORY_PATH)
    loaded_history = torch.load(HISTORY_PATH)
    model.eval()
# Define the path where you saved the weights

import os
# 1. Mount Google Drive

SAVE_DIR = "/content/drive/MyDrive/grokking_model"
os.makedirs(SAVE_DIR, exist_ok=True) # Create the folder if it doesn't exist

MODEL_PATH = os.path.join(SAVE_DIR, "model_state_dict.pt")
HISTORY_PATH = os.path.join(SAVE_DIR, "history.pt")

torch.save(trained_model.state_dict(), MODEL_PATH)
print(f"✅ Model weights saved to: {MODEL_PATH}")
torch.save(history, HISTORY_PATH)

print(f"✅ History dictionary saved to: {HISTORY_PATH}")

import torch
import torch.nn as nn
import torch.nn.functional as F
import matplotlib.pyplot as plt
from tqdm import tqdm
import numpy as np
import matplotlib.cm as cm

# Assume the following are already in your environment:
# model: the pre-trained HookedTransformer model
# config: the dictionary with model and training parameters (p, d_model, etc.)
# test_data: your data tensors

# --- 1. Custom STE Functions ---

def _rectangle(x):
    return ((x > -0.5) & (x < 0.5)).to(x.dtype)

class StepFunction(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x, threshold, bandwidth):
        ctx.save_for_backward(x, threshold); ctx.bandwidth = bandwidth
        return (x > threshold).to(x.dtype)
    @staticmethod
    def backward(ctx, output_grad):
        x, threshold = ctx.saved_tensors; bandwidth = ctx.bandwidth
        grad_threshold = -(1.0 / bandwidth) * _rectangle((x - threshold) / bandwidth) * output_grad
        return torch.zeros_like(x), grad_threshold, None

class JumpReLUFunction(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x, threshold, bandwidth):
        ctx.save_for_backward(x, threshold); ctx.bandwidth = bandwidth
        return x * (x > threshold)
    @staticmethod
    def backward(ctx, output_grad):
        x, threshold = ctx.saved_tensors; bandwidth = ctx.bandwidth
        grad_x = (x > threshold).to(x.dtype) * output_grad
        grad_threshold = -(threshold / bandwidth) * _rectangle((x - threshold) / bandwidth) * output_grad
        return grad_x, grad_threshold, None

# --- 2. JumpReLU_SAE Class Definition ---
class JumpReLU_SAE(nn.Module):
    def __init__(self, d_model, d_sae, initial_log_threshold=0.001, bandwidth=0.001):
        super().__init__()
        self.d_model, self.d_sae, self.bandwidth = d_model, d_sae, bandwidth
        self.W_enc = nn.Parameter(torch.nn.init.kaiming_uniform_(torch.empty(d_model, d_sae)))
        self.b_enc = nn.Parameter(torch.zeros(d_sae)); self.b_dec = nn.Parameter(torch.zeros(d_model))
        self.log_threshold = nn.Parameter(torch.log(torch.full((d_sae,), initial_log_threshold)))

    @property
    def W_dec_normed(self):
        return self.W_enc.t() / (torch.norm(self.W_enc.t(), p=2, dim=1, keepdim=True) + 1e-8)

    def forward(self, x):
        pre_activations = F.relu(x @ self.W_enc + self.b_enc)
        threshold = torch.exp(self.log_threshold)
        feature_magnitudes = JumpReLUFunction.apply(pre_activations, threshold, self.bandwidth)
        x_reconstructed = feature_magnitudes @ self.W_dec_normed + self.b_dec
        return x_reconstructed, feature_magnitudes, pre_activations

# --- 3. Activation Harvesting and Analysis Functions ---

@torch.no_grad()
def get_activations(model, data, layer, device, batch_size):
    model.eval(); activations = []
    print("Harvesting activations...")
    for i in tqdm(range(0, len(data), batch_size)):
        batch = data[i:i+batch_size].to(device)
        if batch.shape[0] == 0: continue
        _, cache = model.run_with_cache(batch)
        activations.append(cache[f"blocks.{layer}.hook_resid_post"][:, -1, :].cpu())
    return torch.cat(activations, dim=0)

@torch.no_grad()
def run_full_analysis(sae, model, p, layer, device, num_features_to_plot=5):
    print("\n--- Running Full Feature Analysis ---"); sae.eval().to(device); model.eval().to(device)
    analytical_inputs = torch.tensor([[i, 0, p] for i in range(p)], device=device)
    _, cache = model.run_with_cache(analytical_inputs)
    activations = cache[f"blocks.{layer}.hook_resid_post"][:, -1, :]
    _, feature_activations, _ = sae(activations)
    feature_variances = torch.var(feature_activations, dim=0)
    top_feature_indices = torch.topk(feature_variances, k=num_features_to_plot).indices

    for feature_idx in top_feature_indices:
        fig, axes = plt.subplots(1, 3, figsize=(21, 5)); fig.suptitle(f"Comprehensive Analysis of Feature {feature_idx.item()}", fontsize=16)
        feature_data = feature_activations[:, feature_idx].cpu()
        axes[0].plot(range(p), feature_data); axes[0].set_title("Feature Activation vs. Input 'a'"); axes[0].grid(True)
        fft_result = torch.fft.fft(feature_data); fft_magnitude = torch.abs(fft_result); freqs = torch.fft.fftfreq(len(feature_data))
        axes[1].bar(freqs[:p//2] * p, fft_magnitude[:p//2]); axes[1].set_title("FFT of Activation Pattern"); axes[1].grid(True)
        feature_vector = sae.W_dec_normed[feature_idx]; logit_influence = feature_vector @ model.W_U
        axes[2].plot(range(p), logit_influence[:p].cpu()); axes[2].set_title("Influence on Output Logits"); axes[2].grid(True)
        plt.tight_layout(rect=[0, 0.03, 1, 0.95]); plt.show()

    feature_vectors = sae.W_dec_normed[top_feature_indices]; cosine_sim_matrix = feature_vectors @ feature_vectors.T
    fig, ax = plt.subplots(figsize=(8, 6)); im = ax.imshow(cosine_sim_matrix.cpu().numpy(), cmap=cm.viridis); plt.colorbar(im)
    ax.set_xticks(np.arange(len(top_feature_indices))); ax.set_yticks(np.arange(len(top_feature_indices)))
    ax.set_xticklabels(top_feature_indices.cpu().numpy()); ax.set_yticklabels(top_feature_indices.cpu().numpy())
    ax.set_title("Cosine Similarity Between Top Feature Vectors"); plt.show()
    return top_feature_indices

@torch.no_grad()
def analyze_feature_ablation(sae, model, layer, device, p, feature_to_ablate, a, b):
    """(Corrected) Analyzes the causal effect of ablating a single feature."""
    print(f"\n--- Causal Ablation Analysis for Feature {feature_to_ablate} ---")
    sae.eval().to(device); model.eval().to(device)
    test_input = torch.tensor([[a, b, p]], device=device)

    # --- THIS IS THE CORRECTED PART ---
    # We select the logits for the final token position BEFORE taking the argmax
    baseline_logits = model(test_input)[:, -1, :]
    baseline_pred = baseline_logits.argmax(-1).item()
    # ------------------------------------

    print(f"Input: ({a} + {b}) % {p} = {(a+b)%p} | Baseline model prediction: {baseline_pred}")

    _, cache = model.run_with_cache(test_input); activation_at_pos = cache[f"blocks.{layer}.hook_resid_post"][:, -1, :]
    _, c, _ = sae(activation_at_pos)
    feature_contribution = c[:, feature_to_ablate].unsqueeze(1) * sae.W_dec_normed[feature_to_ablate]

    def ablation_hook(resid_post, hook):
        resid_post[:, -1, :] -= feature_contribution
        return resid_post
    ablated_logits = model.run_with_hooks(test_input, fwd_hooks=[(f"blocks.{layer}.hook_resid_post", ablation_hook)])

    # Also select the final token's logits here
    final_ablated_logits = ablated_logits[:, -1, :]
    ablated_pred = final_ablated_logits.argmax(-1).item()
    print(f"Prediction after ablating feature {feature_to_ablate}: {ablated_pred} | Effect: {'SUCCESS' if ablated_pred != baseline_pred else 'NO CHANGE'}")

# --- 4. Main Execution Block ---
if 'model' in locals() and 'test_data' in locals():
    jumprelu_sae_config = {
        'd_sae': config['d_model'] * 4, 'l0_lambda': 0.004, 'lr': 7e-5,
        'epochs': 25, 'batch_size': 4096, 'initial_threshold': 0.001,
        'bandwidth': 0.001, 'target_layer': 0
    }
    device = config['device']

    activations_data = get_activations(model, test_data, jumprelu_sae_config['target_layer'], device, jumprelu_sae_config['batch_size'])
    print(f"\n--- Training the JumpReLU Sparse Autoencoder ---")
    sae = JumpReLU_SAE(config['d_model'], jumprelu_sae_config['d_sae'], initial_log_threshold=jumprelu_sae_config['initial_threshold'], bandwidth=jumprelu_sae_config['bandwidth']).to(device)
    optimizer = torch.optim.Adam(sae.parameters(), lr=jumprelu_sae_config['lr'])
    num_batches = len(activations_data) // jumprelu_sae_config['batch_size']

    for epoch in range(jumprelu_sae_config['epochs']):
        pbar = tqdm(range(num_batches), desc=f"Epoch {epoch+1}/{jumprelu_sae_config['epochs']}")
        for i in pbar:
            batch = activations_data[i*jumprelu_sae_config['batch_size']:(i+1)*jumprelu_sae_config['batch_size']].to(device)
            optimizer.zero_grad(); x_hat, c, pre_act = sae(batch)
            recon_loss = F.mse_loss(x_hat, batch, reduction='none').sum(dim=-1)
            threshold = torch.exp(sae.log_threshold)
            l0_norm = StepFunction.apply(pre_act, threshold, sae.bandwidth).sum(dim=-1)
            sparsity_loss = jumprelu_sae_config['l0_lambda'] * l0_norm
            loss = (recon_loss + sparsity_loss).mean(); loss.backward(); optimizer.step()
            pbar.set_postfix({"loss": f"{loss.item():.2f}", "L0": f"{l0_norm.mean().item():.2f}"})

    top_indices = run_full_analysis(sae, model, config['p'], jumprelu_sae_config['target_layer'], device)

    if top_indices is not None and len(top_indices) > 0:
        analyze_feature_ablation(sae, model, jumprelu_sae_config['target_layer'], device, config['p'], top_indices[0].item(), a=10, b=20)
        analyze_feature_ablation(sae, model, jumprelu_sae_config['target_layer'], device, config['p'], top_indices[1].item(), a=10, b=20)
else:
    print("Please ensure 'model' and 'test_data' are loaded in the environment before running.")

import torch
import torch.nn as nn
import pandas as pd
import numpy as np
from torchinfo import summary
from collections import defaultdict
import io
import contextlib
from transformer_lens import HookedTransformer
from sklearn.decomposition import PCA

def _fingerprint_tensor(tensor: torch.Tensor) -> dict:
    """Computes a set of statistics for a single parameter tensor."""
    stats = {}
    t = tensor.detach().float().cpu()

    stats['shape'] = tuple(t.shape)
    stats['norm_l2'] = torch.linalg.norm(t).item()
    stats['mean'] = t.mean().item()
    stats['std'] = t.std().item()
    stats['min'] = t.min().item()
    stats['max'] = t.max().item()
    stats['sparsity_1e-5'] = (torch.sum(t.abs() < 1e-5) / t.numel()).item()

    if t.dim() == 2:
        svd_vals = torch.linalg.svdvals(t)
        stats['svd_max'] = svd_vals[0].item()
        stats['stable_rank'] = (svd_vals.sum()**2 / (svd_vals**2).sum()).item()
        stats['rank'] = torch.linalg.matrix_rank(t).item()

    return stats

def _create_ascii_pca_plot(data: torch.Tensor, width: int = 50, height: int = 20) -> str:
    """Creates a 2D ASCII scatter plot of the data using PCA."""
    if data.shape[0] < 2: return "Not enough data points for PCA plot."

    pca = PCA(n_components=2)
    try:
        proj = pca.fit_transform(data.cpu().numpy())  # simplified - no detach needed
    except Exception:
        return "PCA failed to converge."

    # Normalize projected data to fit within the grid dimensions
    min_x, max_x = proj[:, 0].min(), proj[:, 0].max()
    min_y, max_y = proj[:, 1].min(), proj[:, 1].max()

    # Avoid division by zero if all points are the same
    if max_x == min_x or max_y == min_y: return "Data has zero variance in projection."

    proj[:, 0] = (proj[:, 0] - min_x) / (max_x - min_x) * (width - 1)
    proj[:, 1] = (proj[:, 1] - min_y) / (max_y - min_y) * (height - 1)

    # Create the grid and plot points
    grid = [[' ' for _ in range(width)] for _ in range(height)]
    for x, y in proj:
        # Flip y-axis for standard plot orientation
        grid[height - 1 - int(y)][int(x)] = '*'

    return "\n".join("".join(row) for row in grid)


def generate_model_cartography(model: nn.Module, example_input_shape: tuple) -> str:
    """
    Generates the definitive comprehensive text report for a PyTorch model.
    """
    with torch.no_grad():  # THE FIX - no more grad tracking nonsense
        report_parts = ["# 🗺️ Model Cartography Report\n"]

        # --- 1. Architectural Overview ---
        report_parts.append("## 🏛️ Architectural Overview")
        s = io.StringIO()
        with contextlib.redirect_stdout(s):
            summary(model, input_size=example_input_shape, dtypes=[torch.long],
                    col_names=("input_size", "output_size", "num_params", "mult_adds"), verbose=0)
        report_parts.append(f"```\n{s.getvalue()}\n```")

        # --- 2. Statistical Fingerprints ---
        report_parts.append("## 🔬 Statistical Fingerprints")
        all_stats = {name: _fingerprint_tensor(param) for name, param in model.named_parameters()}
        stats_df = pd.DataFrame.from_dict(all_stats, orient='index').round(4)
        report_parts.append(stats_df.to_markdown())

        # --- 3. Attention Head Analysis ---
        report_parts.append("## 👁️ Attention Head Deep Dive & Pattern Analysis")
        attn_weights = defaultdict(dict)
        for name, param in model.named_parameters():
            if '.attn.W_' in name and param.dim() > 2:
                parts = name.split('.')
                weight_type = parts[3]
                block_idx = int(parts[1])
                for head_idx in range(param.shape[0]):
                    key = f"B{block_idx}-H{head_idx}"
                    attn_weights[key][weight_type] = param[head_idx]

        if attn_weights:
            # Part A: Statistical & Functional Properties
            head_analysis = []
            for key, weights in attn_weights.items():
                W_Q, W_K, W_V, W_O = (weights.get(t) for t in ['W_Q', 'W_K', 'W_V', 'W_O'])
                if all(t is not None for t in [W_Q, W_K, W_V, W_O]):
                    analysis = {'head': key}
                    # QK Orthogonality
                    q_norm, k_norm = W_Q.norm(), W_K.norm()
                    if q_norm > 0 and k_norm > 0:
                        analysis['QK_diff'] = torch.linalg.norm(W_Q / q_norm - W_K / k_norm).item()
                    # OV Composition (functional analysis)
                    composed_vo = W_V @ W_O
                    analysis['VO_stable_rank'] = _fingerprint_tensor(composed_vo).get('stable_rank')
                    head_analysis.append(analysis)

            if head_analysis:
                report_parts.append("### Functional & Statistical Properties")
                report_parts.append("`QK_diff`≈1.41 indicates orthogonal Q/K projections. `VO_stable_rank` shows the head's functional complexity (low=copying, high=complex).")
                head_df = pd.DataFrame(head_analysis).round(4)
                report_parts.append(head_df.to_markdown(index=False))

            # Part B: Positional Attention Patterns
            report_parts.append("\n### Positional Attention Patterns")
            W_pos = model.pos_embed.W_pos
            pattern_report = [ "Data-independent attention patterns. Rows are query_pos, columns are key_pos." ]
            for key, weights in attn_weights.items():
                W_Q, W_K = weights.get('W_Q'), weights.get('W_K')
                if W_Q is not None and W_K is not None:
                    QK_circuit = W_Q @ W_K.T
                    pos_attention_logits = W_pos @ QK_circuit @ W_pos.T
                    pos_attention_pattern = torch.softmax(pos_attention_logits, dim=-1)
                    header = f"**{key}**:"
                    pattern_str = "```\n" + np.array2string(pos_attention_pattern.cpu().numpy(), formatter={'float_kind': lambda x: "%.2f" % x}) + "\n```"
                    pattern_report.append(header + "\n" + pattern_str)
            if len(pattern_report) > 1: report_parts.append("\n".join(pattern_report))

        # --- 4. Embedding Geometry Analysis ---
        report_parts.append("## ジオメトリ Embedding Geometry Analysis")
        report_parts.append("Visualizing the geometric structure of the learned token embeddings.")

        # Get d_vocab robustly from the embedding matrix shape.
        d_vocab = model.embed.W_E.shape[0]
        num_tokens = d_vocab - 1
        W_E = model.embed.W_E[:num_tokens, :]

        # Part A: ASCII PCA Plot
        report_parts.append("\n### PCA Projection of W_E")
        pca_plot = _create_ascii_pca_plot(W_E)
        report_parts.append(f"```\n{pca_plot}\n```")

        # Part B: Cosine Similarity Matrix
        report_parts.append("\n### W_E Cosine Similarity")
        W_E_normalized = W_E / W_E.norm(dim=-1, keepdim=True)
        cosine_sim_matrix = W_E_normalized @ W_E_normalized.T
        patch_size = 16
        patch = cosine_sim_matrix[:patch_size, :patch_size]
        header = f"Top-Left {patch_size}x{patch_size} Patch:"
        patch_str = "```\n" + np.array2string(patch.cpu().numpy(), formatter={'float_kind': lambda x: "%.2f" % x}) + "\n```"
        report_parts.append(header + "\n" + patch_str)

        # --- 5. Key MLP Neuron Analysis ---
        report_parts.append("## 💡 Key MLP Neuron Analysis")
        report_parts.append("Identifying the 'most important' neurons in the MLP layer by L2 norm of their connection weights.")
        W_in = model.blocks[0].mlp.W_in
        W_out = model.blocks[0].mlp.W_out
        top_k = 5
        in_norms, out_norms = W_in.norm(dim=0), W_out.norm(dim=1)
        top_in_indices = torch.topk(in_norms, top_k).indices
        top_out_indices = torch.topk(out_norms, top_k).indices
        report_parts.append(f"Top {top_k} neurons by **input** weight norm: {top_in_indices.tolist()}")
        report_parts.append(f"Top {top_k} neurons by **output** weight norm: {top_out_indices.tolist()}")

        return "\n\n---\n\n".join(report_parts)

generate_model_cartography(model, train_data.shape)

#model.state_dict()
p=config['p']

try:
    from neel_plotly.plot import line

    train_losses = history['train_loss']
    test_losses = history['test_loss']
    steps = history['steps']

    print("\nPlotting training and test loss...")
    line(
        [train_losses, test_losses],
        x=steps,
        xaxis="Step",
        yaxis="Loss",
        log_y=False,
        title="Training Curve for Modular Addition",
        line_labels=['train', 'test'],
    )
except ImportError:
    print("\nPlease install 'neel-plotly' to generate the plot:")

import transformer_lens.utils as utils

def imshow(tensor, renderer=None, xaxis="", yaxis="", **kwargs):
    px.imshow(utils.to_numpy(tensor), color_continuous_midpoint=0.0, color_continuous_scale="RdBu", labels={"x":xaxis, "y":yaxis}, **kwargs).show(renderer)


def scatter(x, y, xaxis="", yaxis="", caxis="", renderer=None, **kwargs):
    x = utils.to_numpy(x)
    y = utils.to_numpy(y)
    px.scatter(y=y, x=x, labels={"x":xaxis, "y":yaxis, "color":caxis}, **kwargs).show(renderer)

original_logits, cache = model.run_with_cache(torch.cat((train_data, test_data), dim=0))
print(original_logits.numel())
W_E = model.embed.W_E[:-1]
print("W_E", W_E.shape)
W_neur = W_E @ model.blocks[0].attn.W_V @ model.blocks[0].attn.W_O @ model.blocks[0].mlp.W_in
print("W_neur", W_neur.shape)
W_logit = model.blocks[0].mlp.W_out @ model.unembed.W_U
print("W_logit", W_logit.shape)

pattern_a = cache["pattern", 0, "attn"][:, :, -1, 0]
pattern_b = cache["pattern", 0, "attn"][:, :, -1, 1]
neuron_acts = cache["post", 0, "mlp"][:, -1, :]
neuron_pre_acts = cache["pre", 0, "mlp"][:, -1, :]

for param_name, param in cache.items():
    print(param_name, param.shape)

model.W_E[:p, :].shape, model.W_E.shape

U, S, Vh = torch.svd(W_E)
line(U[:, :8].T, title="Principal Components of the embedding", xaxis="Input Vocabulary")

fourier_basis = []
fourier_basis_names = []
fourier_basis.append(torch.ones(p))
fourier_basis_names.append("Constant")
for freq in range(1, p//2+1):
    fourier_basis.append(torch.sin(torch.arange(p)*2 * torch.pi * freq / p))
    fourier_basis_names.append(f"Sin {freq}")
    fourier_basis.append(torch.cos(torch.arange(p)*2 * torch.pi * freq / p))
    fourier_basis_names.append(f"Cos {freq}")
fourier_basis = torch.stack(fourier_basis, dim=0).to(device)
fourier_basis = fourier_basis/fourier_basis.norm(dim=-1, keepdim=True)
imshow(fourier_basis, xaxis="Input", yaxis="Component", y=fourier_basis_names)

"""## Dim Reduction (METHODS HAVE BIASED!)"""

import torch
import plotly.express as px
import plotly.graph_objects as go
from sklearn.decomposition import PCA
import numpy as np


# 1. Get the first 'p' embeddings and run PCA
W_E_numeric = model.W_E[:p, :]
W_E_numpy = W_E_numeric.cpu().detach().numpy()
pca = PCA(n_components=2)
components = pca.fit_transform(W_E_numpy)

# 2. Define color values based on the integer sequence from 0 to p-1.
color_values = np.arange(p)

# 3. Create the scatter plot, now coloring by the integer value.
fig = px.scatter(
    x=components[:, 0],
    y=components[:, 1],
    text=[str(i) for i in range(p)],
    color=color_values, # Color points by their integer value (0, 1, 2, ...)
    color_continuous_scale='Plasma_r', # A sequential scale that starts bright (yellow) and gets darker.
                                       # The '_r' suffix reverses the default 'Plasma' scale.
)

# 4. Update the layout to reflect the new coloring scheme.
fig.update_layout(
    title_text=f'PCA of Embeddings for numbers 0 to {p-1} (Colored by Value)',
    title_x=0.5,
    width=700,
    height=700,
    plot_bgcolor='rgba(250, 250, 250, 1)',
    paper_bgcolor='rgba(255, 255, 255, 1)',
    margin=dict(l=50, r=50, t=100, b=50),
    coloraxis_showscale=True # We now want to show the color bar.
)

# 5. Enforce a 1:1 aspect ratio and clean up the axes.
fig.update_yaxes(
    scaleanchor="x",
    scaleratio=1,
    showgrid=False,
    zeroline=False,
    showline=False,
    showticklabels=False,
    title=None
)
fig.update_xaxes(
    showgrid=False,
    zeroline=False,
    showline=False,
    showticklabels=False,
    title=None
)

# 6. Style the markers and text for better readability.
fig.update_traces(
    marker=dict(size=14,
                line=dict(width=1,
                            color='DarkSlateGrey')),
    textposition='middle center',
    textfont=dict(
        family="Arial, sans-serif",
        size=9,
        color="black" # Changed to black for better visibility against the light yellow start of the gradient.
    )
)

fig.show()

# 1. --- PCA and Component Preparation ---
W_E_numpy = model.W_E[:p, :].cpu().detach().numpy()
pca = PCA(n_components=3)
components = pca.fit_transform(W_E_numpy)

# 2. --- Define Animation Parameters ---
operation_steps = [1, 10, 60]
TAIL_LENGTH = 8 # How many previous steps to show in the tail

# 3. --- Create the Base Figure and All Traces ---
fig = go.Figure()

# Add the static manifold path as a semi-transparent background
fig.add_trace(go.Scatter3d(
    x=components[:, 0], y=components[:, 1], z=components[:, 2],
    mode='lines', line=dict(color='lightgrey', width=2), hoverinfo='none'
))

# Create one "tail" trace for each operation type
for i, step_size in enumerate(operation_steps):
    is_visible = (i == 0) # Only the first operation is visible initially

    # Generate initial data for the tail
    initial_indices = [(0 - k * step_size) % p for k in range(TAIL_LENGTH)]
    initial_indices.reverse() # Order from oldest to newest

    # Create the gradient values for color and size
    gradient_values = np.linspace(0, 1, TAIL_LENGTH)

    fig.add_trace(go.Scatter3d(
        x=components[initial_indices, 0],
        y=components[initial_indices, 1],
        z=components[initial_indices, 2],
        mode='markers',
        marker=dict(
            size=gradient_values * 12,  # Newest point is biggest
            color=gradient_values,      # Newest point is "hottest"
            colorscale='YlOrRd',        # Yellow -> Orange -> Red gradient
            showscale=False,
            sizemin=2
        ),
        hoverinfo='none',
        visible=is_visible,
        name=f'Tail +{step_size}'
    ))

# 4. --- Generate Animation Frames ---
frames = []
for n in range(p):
    frame_data = []
    for step_size in operation_steps:
        # Get the indices for the current tail
        current_pos = n
        indices = [(current_pos - k * step_size) % p for k in range(TAIL_LENGTH)]
        indices.reverse()

        frame_data.append(go.Scatter3d(
            x=components[indices, 0],
            y=components[indices, 1],
            z=components[indices, 2],
        ))

    frames.append(go.Frame(data=frame_data, traces=[1, 2, 3], name=str(n)))

fig.frames = frames

# 5. --- Create UI Controls ---
slider = go.layout.Slider(steps=[{'args': [[str(n)], {'frame': {'duration': 300}, 'mode': 'immediate', 'transition': {'duration': 100}}],
                                  'label': str(n), 'method': 'animate'} for n in range(p)])
updatemenus = [
    { # Play/Pause Buttons
        'buttons': [
            {'args': [None, {'frame': {'duration': 200}, 'fromcurrent': True, 'transition': {'duration': 0}}],
             'label': 'Play', 'method': 'animate'},
            {'args': [[None], {'frame': {'duration': 0}, 'mode': 'immediate', 'transition': {'duration': 0}}],
             'label': 'Pause', 'method': 'animate'}
        ], 'direction': 'left', 'pad': {'r': 10, 't': 87}, 'type': 'buttons', 'x': 0.1, 'xanchor': 'right', 'y': 0, 'yanchor': 'top'
    },
    { # Operation Selector Dropdown
        'buttons': [
            {'args': [{'visible': [True, True, False, False]}], 'label': '+1', 'method': 'restyle'},
            {'args': [{'visible': [True, False, True, False]}], 'label': '+10', 'method': 'restyle'},
            {'args': [{'visible': [True, False, False, True]}], 'label': '+60', 'method': 'restyle'}
        ], 'direction': 'down', 'pad': {'r': 10, 't': 87}, 'active': 0, 'type': 'dropdown', 'x': 0.01, 'xanchor': 'left', 'y': 1, 'yanchor': 'top'
    }
]

# 6. --- Final Layout ---
fig.update_layout(
    title_text='Animating Modular Addition with a Fading Tail', title_x=0.5,
    width=1000, height=800, showlegend=False,
    scene=dict(
        xaxis=dict(visible=False), yaxis=dict(visible=False), zaxis=dict(visible=False),
        aspectmode='data', camera_eye=dict(x=1.8, y=1.8, z=1.4)
    ),
    sliders=[slider],
    updatemenus=updatemenus
)

fig.show()

import pandas as pd

# Assuming 'components' is your (p, 3) numpy array and 'p' is the modulus

# Create a DataFrame from the 3D vectors
df = pd.DataFrame(components, columns=['x', 'y', 'z'])

# Add the original number as a new column
df['number'] = range(p)

# Reorder columns for clarity
df = df[['number', 'x', 'y', 'z']]

# Display the first 5 rows
df

!pip install umap-learn scipy

import torch
import plotly.graph_objects as go
import numpy as np
import umap.umap as UMAP
from scipy.spatial import Delaunay

# ==============================================================================
# 1. --- DATA PREPARATION AND UMAP ---
# ==============================================================================

# --- Assume 'model' is a pre-trained model object and 'p' is the modulus ---
# For example:
# p = 113
# model = ... your trained model ...

# Get the first 'p' embeddings from the model
W_E_numeric = model.W_E[:p, :]
W_E_numpy = W_E_numeric.cpu().detach().numpy()

# Use UMAP to find the 3D manifold structure
reducer = UMAP( # FIX: Call the directly imported UMAP class.
    n_components=3,
    n_neighbors=10,
    min_dist=0.1,
    metric='cosine'
)
components = reducer.fit_transform(W_E_numpy)

# Compute the Delaunay triangulation on the UMAP result
tri = Delaunay(components)

# ==============================================================================
# 2. --- PLOT PARAMETERS ---
# ==============================================================================
text_labels = [str(i) for i in range(p)]
DISTANCE_THRESHOLD = 30 # How far apart numbers must be to draw a "wrap-around" line

# ==============================================================================
# 3. --- BUILD THE PLOT WITH LAYERED TRACES ---
# ==============================================================================
fig = go.Figure()

# --- TRACE 1: The main sequential path (0 -> 1 -> 2...) ---
# This trace connects the points in their numerical order.
fig.add_trace(go.Scatter3d(
    x=components[:, 0], y=components[:, 1], z=components[:, 2],
    mode='lines',
    line=dict(color="lightblue", width=2),
    hoverinfo='none',
    name='Sequential Path'
))

# --- TRACE 2: Filtered "wrap-around" lines from Delaunay triangulation ---
# This trace shows non-local connections found by the triangulation,
# highlighting the cyclical nature of the manifold.
wrap_around_lines_x, wrap_around_lines_y, wrap_around_lines_z = [], [], []
for simplex in tri.simplices:
    # A simplex in 3D is a tetrahedron (4 points)
    for i in range(4):
        for j in range(i + 1, 4):
            p1_idx, p2_idx = simplex[i], simplex[j]
            # We only draw lines between points that are far apart numerically
            # but close in the embedding space.
            if abs(p1_idx - p2_idx) > DISTANCE_THRESHOLD:
                wrap_around_lines_x.extend([components[p1_idx, 0], components[p2_idx, 0], None])
                wrap_around_lines_y.extend([components[p1_idx, 1], components[p2_idx, 1], None])
                wrap_around_lines_z.extend([components[p1_idx, 2], components[p2_idx, 2], None])

fig.add_trace(go.Scatter3d(
    x=wrap_around_lines_x, y=wrap_around_lines_y, z=wrap_around_lines_z,
    mode='lines',
    line=dict(color='lightgoldenrodyellow', width=1),
    opacity=0.3,
    hoverinfo='none',
    name='Non-Local Connections'
))

# --- TRACE 3: The points and their labels ---
# This trace plots the individual embedding points and their corresponding numbers.
fig.add_trace(go.Scatter3d(
    x=components[:, 0], y=components[:, 1], z=components[:, 2],
    mode='markers+text',
    text=text_labels,
    textposition='middle right',
    textfont=dict(color='black', size=10),
    marker=dict(
        size=6,
        color=components[:, 2], # Color by Z-axis value for depth perception
        colorscale='Plasma',
        showscale=False
    ),
    name='Embeddings'
))

# ==============================================================================
# 4. --- FINAL LAYOUT AND STYLING ---
# ==============================================================================
fig.update_layout(
    title_text='UMAP of Learned Manifold for Modular Addition',
    title_x=0.5,
    width=900, height=900,
    showlegend=False,
    scene=dict(
        xaxis=dict(visible=False),
        yaxis=dict(visible=False),
        zaxis=dict(visible=False),
        aspectmode='data', # Ensures the aspect ratio is not distorted
        camera_eye=dict(x=1.5, y=1.5, z=1.5) # Set initial camera angle
    )
)

fig.show()

import torch
import plotly.express as px
import umap
import numpy as np

# --- Assume 'model' is trained and 'p' is your modulus (113) ---
p = config['p']

# 1. Get the numeric token embeddings and convert to NumPy
W_E_numeric = model.W_E[:p, :]
W_E_numpy = W_E_numeric.cpu().detach().numpy()

# 2. Set up and run the UMAP reducer
# n_neighbors: Controls the balance between local and global structure.
# min_dist: Controls how tightly UMAP is allowed to pack points together.
# random_state: Ensures the result is reproducible.
reducer = umap.UMAP(
    n_neighbors=100,
    min_dist=0.01,
    n_components=2,
    random_state=42,
)

# Fit the data and transform it to 2D
embedding = reducer.fit_transform(W_E_numpy)
print("Shape of UMAP embedding:", embedding.shape)

# 3. Calculate the angle of each point for coloring
angles = np.arctan2(embedding[:, 1], embedding[:, 0])

# 4. Create the scatter plot
fig = px.scatter(
    x=embedding[:, 0],
    y=embedding[:, 1],
    text=[str(i) for i in range(p)],
    color=angles,
    color_continuous_scale=px.colors.cyclical.HSV,
)

# 5. Apply the styling to make it a clean, square visual
fig.update_layout(
    title_text='UMAP of Token Embeddings (Colored by Angle)',
    title_x=0.5,
    width=700,
    height=700,
    plot_bgcolor='rgba(250, 250, 250, 1)',
    paper_bgcolor='rgba(255, 255, 255, 1)',
    margin=dict(l=50, r=50, t=100, b=50),
    coloraxis_showscale=False
)

fig.update_yaxes(
    scaleanchor="x", scaleratio=1, showgrid=False, zeroline=False,
    showline=False, showticklabels=False, title=None
)
fig.update_xaxes(
    showgrid=False, zeroline=False, showline=False,
    showticklabels=False, title=None
)

fig.update_traces(
    marker=dict(size=14, line=dict(width=1, color='DarkSlateGrey')),
    textposition='middle center',
    textfont=dict(family="Arial, sans-serif", size=9, color="white")
)

fig.show()

from sklearn.manifold import TSNE
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

def plot_tsne(embeddings, labels, perplexity=10):
    tsne = TSNE(n_components=2, random_state=2023, verbose=1, max_iter=5000, perplexity=perplexity)
    X_embedded = tsne.fit_transform(embeddings)
    df = pd.DataFrame(X_embedded, columns=["x0", "x1"])
    df["label"] = labels
    plt.figure(figsize=(8,6))
    g = sns.scatterplot(
    x="x0", y="x1",
    hue="label",
    palette=sns.color_palette("hls", 15),
    data=df,
    legend="full",alpha=0.3)
    g.set_title("random_model_dataset")
    plt.show()

plot_tsne(W_E_numpy, np.arange(113))

"""## Attention Patterns"""

cache["post", 0, "mlp"].shape

imshow(cache["pattern", 0].mean(dim=0)[:, -1, :], title="Average Attention Pattern per Head", xaxis="Source", yaxis="Head", x=['a', 'b', '='])

"""Interesting... the "=" symbol should NOT have ANY attention ... but has ~0.15"""

imshow(cache["pattern", 0][5][:, -1, :], title="Average Attention Pattern per Head", xaxis="Source", yaxis="Head", x=['a', 'b', '='])

# --- Create a structured grid of all possible inputs ---
p = config['p']
device = model.cfg.device

# Create every possible 'a' and 'b'
all_a = torch.arange(p, device=device)
all_b = torch.arange(p, device=device)

# Create the grid
grid_a, grid_b = torch.meshgrid(all_a, all_b, indexing='ij')

# Stack them into the (a, b, '=') format
# The shape will be [p, p, 3]
full_grid_prompts = torch.stack([
    grid_a,
    grid_b,
    torch.full_like(grid_a, p)
], dim=-1)

# Reshape for the model: [p*p, 3] -> [12769, 3]
full_grid_flat = full_grid_prompts.reshape(-1, 3)
print("Shape of the full grid input:", full_grid_flat.shape)

# --- Now run the structured grid through the model ---
with torch.no_grad():
    _, full_cache = model.run_with_cache(full_grid_flat)

# --- Now you can analyze the *entire* activation space ---
# For example, let's look at the activations for a single neuron (e.g., neuron 42)
neuron_idx = 42
neuron_activations = full_cache["post", 0, "mlp"][:, -1, neuron_idx]

# Reshape the activations back into a 2D grid for plotting
activation_grid = neuron_activations.reshape(p, p)

# Plot it!
imshow(
    activation_grid,
    title=f"Activations of Neuron {neuron_idx}",
    xaxis="Input 'b'",
    yaxis="Input 'a'"
)

imshow(cache["pattern", 0][:, 0, -1, 0].reshape(p, p), title="Attention for Head 0 from a -> =", xaxis="b", yaxis="a")

imshow(
    einops.rearrange(cache["pattern", 0][:, :, -1, 0], "(a b) head -> head a b", a=p, b=p),
    title="Attention for Head 0 from a -> =", xaxis="b", yaxis="a", facet_col=0)

cache["post", 0, "mlp"].shape
#should be torch.Size([12769, 3, 512])

# --- IMPORTANT: Re-run the model with the full grid to get the right cache ---
print("Generating cache for the full 113x113 grid...")

with torch.no_grad():
    _, cache = model.run_with_cache(full_grid_flat)

print("✅ Cache generated. Shape of MLP activations:", cache["post", 0, "mlp"].shape)


# --- NOW your plotting code will work ---
p = 113 # Ensure p is defined

# This takes the attention from 'a' to '=' for ALL heads and rearranges
# from shape [12769, 4] into [4, 113, 113]
attention_to_plot = einops.rearrange(
    cache["pattern", 0][:, :, -1, 0],
    "(a b) head -> head a b",
    a=p, b=p
)

imshow(
    attention_to_plot,
    title="Attention from Source 'a' to Destination '='",
    xaxis="Input 'b'",
    yaxis="Input 'a'",
    facet_col=0, # This creates one subplot per head
    facet_col_wrap=2, # Optional: wraps the 4 plots into a 2x2 grid
)

imshow(
    einops.rearrange(cache["pattern", 0][:, :, -1, 0], "(a b) head -> head a b", a=p, b=p),
    title="Attention for Head 0 from a -> =", xaxis="b", yaxis="a", facet_col=0)



"""## Explaining Algorithm

### Analyse the Embedding - It's a Lookup Table!
"""

U, S, Vh = torch.svd(W_E)
line(U[:, :8].T, title="Principal Components of the embedding", xaxis="Input Vocabulary")

fourier_basis = []
fourier_basis_names = []
fourier_basis.append(torch.ones(p))
fourier_basis_names.append("Constant")
for freq in range(1, p//2+1):
    fourier_basis.append(torch.sin(torch.arange(p)*2 * torch.pi * freq / p))
    fourier_basis_names.append(f"Sin {freq}")
    fourier_basis.append(torch.cos(torch.arange(p)*2 * torch.pi * freq / p))
    fourier_basis_names.append(f"Cos {freq}")
fourier_basis = torch.stack(fourier_basis, dim=0).to(device)
fourier_basis = fourier_basis/fourier_basis.norm(dim=-1, keepdim=True)
imshow(fourier_basis, xaxis="Input", yaxis="Component", y=fourier_basis_names)

line(fourier_basis[:8], xaxis="Input", line_labels=fourier_basis_names[:8], title="First 8 Fourier Components")
line(fourier_basis[25:29], xaxis="Input", line_labels=fourier_basis_names[25:29], title="Middle Fourier Components")

imshow(fourier_basis @ fourier_basis.T, title="All Fourier Vectors are Orthogonal")

"""### Analyse the Embedding"""

imshow(fourier_basis @ W_E, yaxis="Fourier Component", xaxis="Residual Stream", y=fourier_basis_names, title="Embedding in Fourier Basis")

line((fourier_basis @ W_E).norm(dim=-1), xaxis="Fourier Component", x=fourier_basis_names, title="Norms of Embedding in Fourier Basis")

key_freqs = [17, 25, 32, 47]
key_freq_indices = [33, 34, 49, 50, 63, 64, 93, 94]
fourier_embed = fourier_basis @ W_E
key_fourier_embed = fourier_embed[key_freq_indices]
print("key_fourier_embed", key_fourier_embed.shape)
imshow(key_fourier_embed @ key_fourier_embed.T, title="Dot Product of embedding of key Fourier Terms")

"""### Key Frequencies"""

line(fourier_basis[[34, 50, 64, 94]], title="Cos of key freqs", line_labels=[34, 50, 64, 94])

line(fourier_basis[[34, 50, 64, 94]].mean(0), title="Constructive Interference")

!pip install torchviz

# %%writefile sweep.yaml

# program: train.py
# method: grid
# metric:
#   name: test_acc
#   goal: maximize
# parameters:
#   lr:
#     values: [0.001]
#   weight_decay:
#     values: [2.5]
#   d_model:
#     values: [64]
#   seed:
#     values: [42]
#   d_ffn:
#     values: [512]

#!wandb sweep sweep.yaml

#!wandb agent discoelysium-neuromatch/uncategorized/keijverd

"""## OLD - REtired utisl"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import matplotlib.pyplot as plt
import numpy as np
from tqdm import tqdm
import matplotlib.cm as cm

# Assume the following are already in your environment from the previous script:
# trained_model: the pre-trained HookedTransformer model
# config: the dictionary with model and training parameters (p, d_model, etc.)
# test_data: your data tensors

# --- 1. Minimal SAE Definition (with helper methods) ---
class SparseAutoencoder(nn.Module):
    def __init__(self, d_model, d_sae):
        super().__init__()
        self.d_model = d_model
        self.d_sae = d_sae
        self.W_enc = nn.Parameter(torch.nn.init.kaiming_uniform_(torch.empty(d_model, d_sae)))
        self.b_enc = nn.Parameter(torch.zeros(d_sae))
        self.b_dec = nn.Parameter(torch.zeros(d_model))

    @property
    def W_dec(self):
        return self.W_enc.t()

    @property
    def W_dec_normed(self):
        return self.W_dec / (torch.norm(self.W_dec, p=2, dim=1, keepdim=True) + 1e-8)

    def encode(self, x):
        return F.relu(x @ self.W_enc + self.b_enc)

    def decode(self, c):
        return c @ self.W_dec_normed + self.b_dec

    def forward(self, x):
        c = self.encode(x)
        x_hat = self.decode(c)
        return x_hat, c

# --- 2. Activation Harvesting ---
@torch.no_grad()
def get_activations(model, data, layer, device, batch_size):
    model.eval()
    activations = []
    print("Harvesting activations...")
    for i in tqdm(range(0, len(data), batch_size)):
        batch = data[i:i+batch_size].to(device)
        if batch.shape[0] == 0: continue
        _, cache = model.run_with_cache(batch)
        res_stream_act = cache[f"blocks.{layer}.hook_resid_post"][:, -1, :]
        activations.append(res_stream_act.cpu())
    return torch.cat(activations, dim=0)


# --- 3. Full Analysis Suite ---
@torch.no_grad()
def run_full_analysis(sae, model, p, layer, device, num_features_to_plot=5):
    """
    Master function to run and plot all analyses for the top features.
    """
    print("\n--- Running Full Feature Analysis ---")
    sae.eval().to(device)
    model.eval().to(device)
    analytical_inputs = torch.tensor([[i, 0, p] for i in range(p)], device=device)
    _, cache = model.run_with_cache(analytical_inputs)
    activations = cache[f"blocks.{layer}.hook_resid_post"][:, -1, :]
    _, feature_activations = sae(activations)

    feature_variances = torch.var(feature_activations, dim=0)
    top_feature_indices = torch.topk(feature_variances, k=num_features_to_plot).indices

    # 1. Plot Activations, FFT, and Unembedding for each top feature
    for feature_idx in top_feature_indices:
        fig, axes = plt.subplots(1, 3, figsize=(21, 5))
        fig.suptitle(f"Comprehensive Analysis of Feature {feature_idx.item()}", fontsize=16)

        # Plot 1: Feature Activation
        feature_data = feature_activations[:, feature_idx].cpu()
        axes[0].plot(range(p), feature_data)
        axes[0].set_title("Feature Activation vs. Input 'a'")
        axes[0].set_xlabel("Input value 'a'")
        axes[0].set_ylabel("Activation")
        axes[0].grid(True, linestyle='--', alpha=0.6)

        # Plot 2: FFT of Activations
        fft_result = torch.fft.fft(feature_data)
        fft_magnitude = torch.abs(fft_result)
        freqs = torch.fft.fftfreq(len(feature_data))
        axes[1].bar(freqs[:p//2] * p, fft_magnitude[:p//2]) # Plot positive frequencies
        axes[1].set_title("FFT of Activation Pattern")
        axes[1].set_xlabel("Frequency Component (k)")
        axes[1].set_ylabel("Magnitude")
        axes[1].grid(True, linestyle='--', alpha=0.6)

        # Plot 3: Unembedding Influence
        feature_vector = sae.W_dec_normed[feature_idx]
        logit_influence = feature_vector @ model.W_U
        axes[2].plot(range(p), logit_influence[:p].cpu())
        axes[2].set_title("Influence on Output Logits")
        axes[2].set_xlabel("Output Token (Number)")
        axes[2].set_ylabel("Logit Change")
        axes[2].grid(True, linestyle='--', alpha=0.6)

        plt.tight_layout(rect=[0, 0.03, 1, 0.95])
        plt.show()

    # 2. Analyze Feature Geometry (Cosine Similarity)
    feature_vectors = sae.W_dec_normed[top_feature_indices]
    cosine_sim_matrix = feature_vectors @ feature_vectors.T

    fig, ax = plt.subplots(figsize=(8, 6))
    im = ax.imshow(cosine_sim_matrix.cpu().numpy(), cmap=cm.viridis)
    ax.set_xticks(np.arange(len(top_feature_indices)))
    ax.set_yticks(np.arange(len(top_feature_indices)))
    ax.set_xticklabels(top_feature_indices.cpu().numpy())
    ax.set_yticklabels(top_feature_indices.cpu().numpy())
    plt.colorbar(im)
    ax.set_title("Cosine Similarity Between Top Feature Vectors")
    plt.show()

    return top_feature_indices # Return for ablation

@torch.no_grad()
def analyze_feature_ablation(sae, model, layer, device, p, feature_to_ablate, a, b):
    """
    Demonstrates the causal effect of ablating a single feature.
    """
    print(f"\n--- Causal Ablation Analysis for Feature {feature_to_ablate} ---")
    sae.eval().to(device)
    model.eval().to(device)

    # 1. Baseline run
    test_input = torch.tensor([[a, b, p]], device=device)
    baseline_logits = model(test_input)
    baseline_pred = baseline_logits.argmax(-1).item()
    print(f"Input: ({a} + {b}) % {p} = {(a+b)%p}")
    print(f"Baseline model prediction: {baseline_pred}")

    # 2. Ablation run
    # Get the feature activation value for this input
    _, cache = model.run_with_cache(test_input)
    activation_at_pos = cache[f"blocks.{layer}.hook_resid_post"][:, -1, :]
    c = sae.encode(activation_at_pos)

    # The vector we need to subtract is the feature's contribution
    feature_vector = sae.W_dec_normed[feature_to_ablate]
    feature_contribution = c[:, feature_to_ablate].unsqueeze(1) * feature_vector

    # Define the hook to subtract this vector from the residual stream
    def ablation_hook(resid_post, hook):
        resid_post[:, -1, :] -= feature_contribution
        return resid_post

    ablated_logits = model.run_with_hooks(
        test_input,
        fwd_hooks=[(f"blocks.{layer}.hook_resid_post", ablation_hook)]
    )
    ablated_pred = ablated_logits.argmax(-1).item()
    print(f"Prediction after ablating feature {feature_to_ablate}: {ablated_pred}")
    print(f"Effect: {'SUCCESS' if ablated_pred != baseline_pred else 'NO CHANGE'}")


# --- Main Execution ---
if 'model' in locals() or 'model' in globals(): # Check if the model exists
    sae_config = {
        'd_sae': config['d_model'] * 4,
        'l1_alpha': 0.005,
        'lr': 3e-4,
        'epochs': 20,
        'batch_size': 512,
        'target_layer': 0
    }
    device = config['device']

    # --- Step 1: Harvest Activations ---
    print("--- 1. Harvesting Activations from Transformer ---")
    activations_data = get_activations(model, test_data, sae_config['target_layer'], device, sae_config['batch_size'])
    print(f"Harvested {activations_data.shape[0]} activation vectors of dim {activations_data.shape[1]}")

    # --- Step 2: Train the SAE ---
    print("\n--- 2. Training the Sparse Autoencoder ---")
    sae = SparseAutoencoder(config['d_model'], sae_config['d_sae']).to(device)
    optimizer = torch.optim.Adam(sae.parameters(), lr=sae_config['lr'])
    num_batches = len(activations_data) // sae_config['batch_size']

    for epoch in range(sae_config['epochs']):
        activations_data = activations_data[torch.randperm(len(activations_data))]
        pbar = tqdm(range(num_batches), desc=f"Epoch {epoch+1}/{sae_config['epochs']}")
        for i in pbar:
            batch = activations_data[i*sae_config['batch_size']:(i+1)*sae_config['batch_size']].to(device)
            optimizer.zero_grad()
            x_hat, c = sae(batch)
            recon_loss = F.mse_loss(x_hat, batch)
            l1_loss = torch.norm(c, p=1, dim=1).mean()
            loss = recon_loss + sae_config['l1_alpha'] * l1_loss
            loss.backward()
            optimizer.step()
            pbar.set_postfix({"loss": f"{loss.item():.4f}", "recon": f"{recon_loss.item():.4f}"})

    # --- Step 3: Run the Full Analysis Suite ---
    top_indices = run_full_analysis(sae, model, config['p'], sae_config['target_layer'], device)

    # --- Step 4: Run Causal Ablation on the top feature ---
    if top_indices is not None and len(top_indices) > 0:
        analyze_feature_ablation(sae, model, sae_config['target_layer'], device, config['p'], top_indices[0].item(), a=10, b=20)
        analyze_feature_ablation(sae, model, sae_config['target_layer'], device, config['p'], top_indices[1].item(), a=10, b=20)

else:
    print("Please ensure the 'model' variable (the trained transformer) is loaded in the environment.")