"""
Manim animations of grokking dynamics.

Visualizes the transition from memorization to algorithmic cognition
in a transformer trained on (a+b) mod 113.

Requires: animations/data/grokking_animation.npz
  (generated by scripts/extract_animation_data.py)

Usage:
    uv run manim -pql animations/grokking.py FourierSpectrumRace
    uv run manim -pql animations/grokking.py EmbeddingCircleFormation
    uv run manim -pql animations/grokking.py NeuronCollapse
    uv run manim -pql animations/grokking.py GrokkingDashboard
"""

from manim import *
import numpy as np
from pathlib import Path

DATA_PATH = Path(__file__).parent / "data" / "grokking_animation.npz"
P = 113

# Color scheme
FREQ_COLORS = {
    12: BLUE,
    101: BLUE,      # mirror of 12
    38: ORANGE,
    75: ORANGE,     # mirror of 38
}
DEFAULT_FREQ_COLOR = GREY


def load_data():
    data = np.load(DATA_PATH)
    return {k: data[k] for k in data.files}


def subsample(data: dict, max_frames: int = 300) -> dict:
    """Subsample checkpoints for smooth animation at reasonable length."""
    n = len(data["steps"])
    if n <= max_frames:
        return data

    # Dense sampling around grokking (steps 2000-5000), sparse elsewhere
    steps = data["steps"]
    indices = []
    for i, s in enumerate(steps):
        if 2000 <= s <= 5000:
            indices.append(i)  # keep all dense checkpoints around grokking
        elif i % max(1, n // max_frames) == 0:
            indices.append(i)

    indices = sorted(set(indices))
    return {k: data[k][indices] if len(data[k].shape) > 0 and data[k].shape[0] == n else data[k]
            for k in data}


def freq_color(k: int) -> ManimColor:
    return FREQ_COLORS.get(k, DEFAULT_FREQ_COLOR)


class FourierSpectrumRace(Scene):
    """Bar chart race showing Fourier frequencies competing over training."""

    def construct(self):
        data = load_data()
        data = subsample(data, max_frames=250)
        steps = data["steps"]
        power = data["fourier_power"]  # [n, P]
        accuracy = data["accuracy"]
        n = len(steps)

        # Normalize power per step
        for i in range(n):
            total = power[i].sum()
            if total > 0:
                power[i] = power[i] / total

        n_bars = 12
        bar_height = 0.4
        max_bar_width = 9.0

        title = Text("Fourier Frequency Competition", font_size=36).to_edge(UP, buff=0.3)
        subtitle = Text("Which frequencies will the network learn?", font_size=20, color=GREY).next_to(title, DOWN, buff=0.1)
        self.add(title, subtitle)

        # Step and accuracy display
        step_text = Text(f"Step: {steps[0]:,}", font_size=24).to_corner(UL, buff=0.5).shift(DOWN * 0.8)
        acc_text = Text(f"Accuracy: {accuracy[0]:.1%}", font_size=24).next_to(step_text, DOWN, aligned_edge=LEFT)
        self.add(step_text, acc_text)

        # Get initial top frequencies
        top_idx = np.argsort(power[0])[::-1][:n_bars]

        # Create initial bars
        bars = VGroup()
        labels = VGroup()
        bar_start_y = 1.5

        for rank, freq_idx in enumerate(top_idx):
            y = bar_start_y - rank * (bar_height + 0.15)
            width = max(power[0, freq_idx] * max_bar_width / max(power[0].max(), 1e-8), 0.05)
            bar = Rectangle(
                width=width, height=bar_height,
                fill_color=freq_color(freq_idx),
                fill_opacity=0.8,
                stroke_width=1,
            ).move_to(LEFT * 2 + RIGHT * width / 2 + UP * y)

            label = Text(f"k={freq_idx}", font_size=18).next_to(bar, LEFT, buff=0.15)
            bars.add(bar)
            labels.add(label)

        self.add(bars, labels)

        # Animate through frames
        frame_dur = 12.0 / n  # ~12 seconds total for the bar evolution
        prev_top = top_idx.copy()

        for i in range(1, n):
            new_top = np.argsort(power[i])[::-1][:n_bars]

            new_bars = VGroup()
            new_labels = VGroup()

            for rank, freq_idx in enumerate(new_top):
                y = bar_start_y - rank * (bar_height + 0.15)
                p_val = power[i, freq_idx]
                max_p = max(power[i].max(), 1e-8)
                width = max(p_val * max_bar_width / max_p, 0.05)

                bar = Rectangle(
                    width=width, height=bar_height,
                    fill_color=freq_color(freq_idx),
                    fill_opacity=0.8,
                    stroke_width=1,
                ).move_to(LEFT * 2 + RIGHT * width / 2 + UP * y)

                label = Text(f"k={freq_idx}", font_size=18).next_to(bar, LEFT, buff=0.15)
                new_bars.add(bar)
                new_labels.add(label)

            new_step = Text(f"Step: {steps[i]:,}", font_size=24).move_to(step_text.get_center())
            new_acc = Text(f"Accuracy: {accuracy[i]:.1%}", font_size=24).move_to(acc_text.get_center())

            # Crossover marker
            anims = [
                Transform(bars, new_bars),
                Transform(labels, new_labels),
                Transform(step_text, new_step),
                Transform(acc_text, new_acc),
            ]

            # Flash at the crossover moment
            if i > 0 and steps[i] >= 3400 and steps[i] <= 3500 and steps[i-1] < 3440:
                flash = Text("CROSSOVER!", font_size=32, color=YELLOW).to_edge(RIGHT, buff=1).shift(UP * 2)
                self.play(*anims, FadeIn(flash), run_time=frame_dur * 3)
                self.play(FadeOut(flash), run_time=0.3)
            else:
                self.play(*anims, run_time=frame_dur)

            prev_top = new_top

        self.wait(2)


class EmbeddingCircleFormation(Scene):
    """Watch embedding vectors organize from random cloud into circles."""

    def construct(self):
        data = load_data()
        data = subsample(data, max_frames=200)
        steps = data["steps"]
        emb_pca = data["embedding_pca"]  # [n, P, 2]
        accuracy = data["accuracy"]
        gini = data["gini"]
        n = len(steps)

        title = Text("Embedding Space: From Noise to Structure", font_size=36).to_edge(UP, buff=0.3)
        self.add(title)

        # Info display
        step_text = Text(f"Step: {steps[0]:,}", font_size=22).to_corner(UL, buff=0.5).shift(DOWN * 0.7)
        acc_text = Text(f"Accuracy: {accuracy[0]:.1%}", font_size=22).next_to(step_text, DOWN, aligned_edge=LEFT)
        gini_text = Text(f"Fourier Gini: {gini[0]:.3f}", font_size=22).next_to(acc_text, DOWN, aligned_edge=LEFT)
        self.add(step_text, acc_text, gini_text)

        # Normalize all PCA projections to fit in view
        all_coords = emb_pca.reshape(-1, 2)
        scale = 2.5 / max(np.abs(all_coords).max(), 1e-8)

        # Create dots colored by number value
        cmap_vals = np.linspace(0, 1, P)
        dot_colors = [interpolate_color(BLUE, RED, v) for v in cmap_vals]

        dots = VGroup()
        for j in range(P):
            x, y = emb_pca[0, j] * scale
            dot = Dot(
                point=[x, y - 0.5, 0],
                radius=0.04,
                color=dot_colors[j],
            )
            dots.add(dot)

        self.add(dots)

        # Animate
        frame_dur = 15.0 / n
        for i in range(1, n):
            new_dots = VGroup()
            for j in range(P):
                x, y = emb_pca[i, j] * scale
                dot = Dot(
                    point=[x, y - 0.5, 0],
                    radius=0.04,
                    color=dot_colors[j],
                )
                new_dots.add(dot)

            new_step = Text(f"Step: {steps[i]:,}", font_size=22).move_to(step_text.get_center())
            new_acc = Text(f"Accuracy: {accuracy[i]:.1%}", font_size=22).move_to(acc_text.get_center())
            new_gini = Text(f"Fourier Gini: {gini[i]:.3f}", font_size=22).move_to(gini_text.get_center())

            self.play(
                Transform(dots, new_dots),
                Transform(step_text, new_step),
                Transform(acc_text, new_acc),
                Transform(gini_text, new_gini),
                run_time=frame_dur,
            )

        self.wait(2)


class NeuronCollapse(Scene):
    """Watch 128 MLP neurons collapse from many frequencies to just 2-3."""

    def construct(self):
        data = load_data()
        data = subsample(data, max_frames=200)
        steps = data["steps"]
        neuron_freqs = data["neuron_freqs"]  # [n, 128]
        accuracy = data["accuracy"]
        n = len(steps)

        title = Text("Neuron Frequency Specialization", font_size=36).to_edge(UP, buff=0.3)
        subtitle = Text("128 MLP neurons choose their frequency", font_size=20, color=GREY).next_to(title, DOWN, buff=0.1)
        self.add(title, subtitle)

        step_text = Text(f"Step: {steps[0]:,}", font_size=22).to_corner(UL, buff=0.5).shift(DOWN * 0.9)
        acc_text = Text(f"Accuracy: {accuracy[0]:.1%}", font_size=22).next_to(step_text, DOWN, aligned_edge=LEFT)
        self.add(step_text, acc_text)

        # We'll show frequencies 1..56 (first half, since mirrors carry same info)
        n_bins = 56
        max_bar_height = 4.0
        bar_width = 0.15
        chart_left = -4.5
        chart_bottom = -2.5

        # Axis
        x_axis = Line(
            start=[chart_left, chart_bottom, 0],
            end=[chart_left + n_bins * bar_width + 0.5, chart_bottom, 0],
            color=WHITE,
        )
        y_axis = Line(
            start=[chart_left, chart_bottom, 0],
            end=[chart_left, chart_bottom + max_bar_height + 0.5, 0],
            color=WHITE,
        )
        x_label = Text("Frequency k", font_size=16).next_to(x_axis, DOWN, buff=0.2)
        y_label = Text("# Neurons", font_size=16).next_to(y_axis, LEFT, buff=0.2).rotate(PI / 2)
        self.add(x_axis, y_axis, x_label, y_label)

        # Frequency tick marks for key frequencies
        for k in [12, 38, 48]:
            tick_x = chart_left + (k - 1) * bar_width
            tick = Text(str(k), font_size=12, color=freq_color(k) if k in FREQ_COLORS else WHITE)
            tick.move_to([tick_x, chart_bottom - 0.3, 0])
            self.add(tick)

        def build_histogram(frame_idx):
            """Build histogram bars for a given frame."""
            freqs = neuron_freqs[frame_idx]
            # Map mirrors to canonical (use min(k, P-k))
            canonical = np.minimum(freqs, P - freqs)
            counts = np.bincount(canonical, minlength=P)[:n_bins + 1]
            max_count = max(counts[1:].max(), 1)

            hist_bars = VGroup()
            for k in range(1, n_bins + 1):
                if counts[k] == 0:
                    continue
                height = counts[k] / max_count * max_bar_height
                x = chart_left + (k - 1) * bar_width
                bar = Rectangle(
                    width=bar_width * 0.9,
                    height=max(height, 0.02),
                    fill_color=freq_color(k),
                    fill_opacity=0.8,
                    stroke_width=0.5,
                ).move_to([x, chart_bottom + height / 2, 0])
                hist_bars.add(bar)
            return hist_bars

        # Count display
        freqs_0 = neuron_freqs[0]
        canonical_0 = np.minimum(freqs_0, P - freqs_0)
        n_unique_0 = len(set(canonical_0))
        count_text = Text(f"Unique frequencies: {n_unique_0}", font_size=22, color=YELLOW).to_corner(UR, buff=0.5).shift(DOWN * 0.9)
        self.add(count_text)

        hist = build_histogram(0)
        self.add(hist)

        frame_dur = 12.0 / n
        for i in range(1, n):
            new_hist = build_histogram(i)
            freqs_i = neuron_freqs[i]
            canonical_i = np.minimum(freqs_i, P - freqs_i)
            n_unique_i = len(set(canonical_i))

            new_step = Text(f"Step: {steps[i]:,}", font_size=22).move_to(step_text.get_center())
            new_acc = Text(f"Accuracy: {accuracy[i]:.1%}", font_size=22).move_to(acc_text.get_center())
            new_count = Text(f"Unique frequencies: {n_unique_i}", font_size=22, color=YELLOW).move_to(count_text.get_center())

            self.play(
                Transform(hist, new_hist),
                Transform(step_text, new_step),
                Transform(acc_text, new_acc),
                Transform(count_text, new_count),
                run_time=frame_dur,
            )

        self.wait(2)


class GrokkingDashboard(Scene):
    """Synchronized 4-panel dashboard of the grokking transition."""

    def construct(self):
        data = load_data()
        data = subsample(data, max_frames=200)
        steps = data["steps"]
        accuracy = data["accuracy"]
        gini_vals = data["gini"]
        norm_vals = data["norm"]
        fourier_power = data["fourier_power"]
        neuron_freqs = data["neuron_freqs"]
        n = len(steps)

        # Title
        title = Text("Grokking: Watching Cognition Emerge", font_size=36, color=WHITE).to_edge(UP, buff=0.2)
        self.add(title)

        # Layout: 2x2 grid
        panel_w, panel_h = 5.5, 2.5
        tl = [-3.5, 1.0, 0]  # top-left center
        tr = [3.5, 1.0, 0]
        bl = [-3.5, -2.0, 0]
        br = [3.5, -2.0, 0]

        # Panel borders and labels
        for center, label_text in [
            (tl, "Test Accuracy"),
            (tr, "Fourier Spectrum"),
            (bl, "Weight Norm"),
            (br, "Neuron Frequencies"),
        ]:
            border = Rectangle(
                width=panel_w, height=panel_h,
                stroke_color=GREY_D, stroke_width=1,
            ).move_to(center)
            label = Text(label_text, font_size=16, color=GREY_B).move_to(
                [center[0], center[1] + panel_h / 2 - 0.2, 0]
            )
            self.add(border, label)

        # Step counter
        step_text = Text(f"Step: {steps[0]:,}", font_size=28).to_edge(DOWN, buff=0.15)
        self.add(step_text)

        # Phase label
        phase_text = Text("MEMORIZATION", font_size=20, color=RED_C).next_to(title, DOWN, buff=0.05)
        self.add(phase_text)

        # ── Panel 1: Accuracy curve (top-left) ──
        acc_axes = Axes(
            x_range=[0, steps[-1], steps[-1] // 4],
            y_range=[0, 1.05, 0.25],
            x_length=panel_w - 0.8,
            y_length=panel_h - 0.7,
            tips=False,
            axis_config={"stroke_width": 1, "font_size": 14, "include_ticks": True},
        ).move_to(tl).shift(DOWN * 0.1)
        self.add(acc_axes)

        # ── Panel 3: Norm curve (bottom-left) ──
        norm_min, norm_max = norm_vals.min() * 0.9, norm_vals.max() * 1.1
        norm_axes = Axes(
            x_range=[0, steps[-1], steps[-1] // 4],
            y_range=[norm_min, norm_max, (norm_max - norm_min) / 4],
            x_length=panel_w - 0.8,
            y_length=panel_h - 0.7,
            tips=False,
            axis_config={"stroke_width": 1, "font_size": 14, "include_ticks": True},
        ).move_to(bl).shift(DOWN * 0.1)
        self.add(norm_axes)

        # Build accuracy and norm paths as sets of line segments
        acc_points = [acc_axes.c2p(steps[0], accuracy[0])]
        norm_points = [norm_axes.c2p(steps[0], norm_vals[0])]

        acc_line = VMobject(stroke_color=GREEN, stroke_width=2)
        acc_line.set_points_as_corners(acc_points * 2)  # need at least 2 points
        norm_line = VMobject(stroke_color=TEAL, stroke_width=2)
        norm_line.set_points_as_corners(norm_points * 2)
        self.add(acc_line, norm_line)

        # ── Panel 2: Fourier spectrum bars (top-right) ──
        # Show top 8 frequencies as bars
        n_fourier_bars = 8
        fourier_bar_group = VGroup()
        self.add(fourier_bar_group)

        # ── Panel 4: Neuron histogram (bottom-right) ──
        neuron_hist_group = VGroup()
        self.add(neuron_hist_group)

        # Animate
        frame_dur = 20.0 / n
        for i in range(1, n):
            # Extend accuracy curve
            acc_points.append(acc_axes.c2p(steps[i], accuracy[i]))
            new_acc_line = VMobject(stroke_color=GREEN, stroke_width=2)
            new_acc_line.set_points_as_corners(acc_points)

            # Extend norm curve
            norm_points.append(norm_axes.c2p(steps[i], norm_vals[i]))
            new_norm_line = VMobject(stroke_color=TEAL, stroke_width=2)
            new_norm_line.set_points_as_corners(norm_points)

            # Fourier bars
            fp = fourier_power[i].copy()
            fp_max = max(fp.max(), 1e-8)
            top_k = np.argsort(fp)[::-1][:n_fourier_bars]
            new_fourier = VGroup()
            bar_w = 0.5
            for rank, freq_idx in enumerate(top_k):
                height = fp[freq_idx] / fp_max * (panel_h - 1.0)
                x = tr[0] - panel_w / 2 + 0.6 + rank * (bar_w + 0.1)
                y = tr[1] - panel_h / 2 + 0.4
                bar = Rectangle(
                    width=bar_w, height=max(height, 0.02),
                    fill_color=freq_color(freq_idx),
                    fill_opacity=0.8, stroke_width=0.5,
                ).move_to([x, y + height / 2, 0])
                lbl = Text(str(freq_idx), font_size=10).move_to([x, y - 0.15, 0])
                new_fourier.add(bar, lbl)

            # Neuron histogram (simplified — show count per canonical freq for top freqs)
            nf = neuron_freqs[i]
            canonical = np.minimum(nf, P - nf)
            counts = np.bincount(canonical, minlength=P)
            top_nf = np.argsort(counts)[::-1][:6]
            new_neuron = VGroup()
            nbar_w = 0.7
            max_nc = max(counts.max(), 1)
            for rank, freq_idx in enumerate(top_nf):
                if counts[freq_idx] == 0:
                    continue
                height = counts[freq_idx] / max_nc * (panel_h - 1.0)
                x = br[0] - panel_w / 2 + 0.6 + rank * (nbar_w + 0.1)
                y = br[1] - panel_h / 2 + 0.4
                bar = Rectangle(
                    width=nbar_w, height=max(height, 0.02),
                    fill_color=freq_color(freq_idx),
                    fill_opacity=0.7, stroke_width=0.5,
                ).move_to([x, y + height / 2, 0])
                lbl = Text(f"k={freq_idx}\n({counts[freq_idx]})", font_size=9).move_to([x, y - 0.2, 0])
                new_neuron.add(bar, lbl)

            # Phase label
            s = steps[i]
            if s < 2000:
                phase = "MEMORIZATION"
                phase_color = RED_C
            elif s < 3500:
                phase = "COMPRESSION"
                phase_color = YELLOW
            elif accuracy[i] < 0.95:
                phase = "CRYSTALLIZATION"
                phase_color = GREEN
            else:
                phase = "COGNITION"
                phase_color = BLUE
            new_phase = Text(phase, font_size=20, color=phase_color).move_to(phase_text.get_center())
            new_step = Text(f"Step: {steps[i]:,}", font_size=28).move_to(step_text.get_center())

            self.play(
                Transform(acc_line, new_acc_line),
                Transform(norm_line, new_norm_line),
                Transform(fourier_bar_group, new_fourier),
                Transform(neuron_hist_group, new_neuron),
                Transform(step_text, new_step),
                Transform(phase_text, new_phase),
                run_time=frame_dur,
            )

        self.wait(3)
